---
title: "Untitled"
author: "Andrea Navarrete"
date: "11/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r cars}
library(tidyverse)

m18 <- read_csv('../data/clean/marathon_2018.csv')
m17 <- read_csv('../data/clean/marathon_2017.csv')
m16 <- read_csv('../data/clean/marathon_2016.csv')
m15 <- read_csv('../data/clean/marathon_2015.csv')

marathon <- rbind(m18, m17, m16, m15)
```

## Including Plots


```{r pressure, echo=FALSE}
glimpse(marathon)
```

## Basic Demographics

### Gender

```{r}
marathon %>% 
  filter(!is.na(gender)) %>% 
  group_by(year) %>% 
  summarise(F = sum(gender == 'F') / n(),
            M = sum(gender == 'M') / n())

marathon %>% 
  filter(!is.na(gender)) %>% 
  group_by(year, type) %>% 
  summarise(F = sum(gender == 'F') / n(),
            M = sum(gender == 'M') / n())
```

### Location

How many we have location?
```{r}
marathon %>% 
  group_by(year) %>% 
  summarise(n = sum((!is.na(country))/ n()))
```

Cities without country
```{r}
without_country <- marathon %>% 
  filter(is.na(country)) %>% 
  group_by(city) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) 
```


Overall
```{r}
marathon %>% 
  filter(!is.na(country)) %>% 
  group_by(year, type) %>% 
  summarise(local = sum(state == 'NY', na.rm = TRUE) / n(),
            national = sum(!is.na(state) & state != 'NY' & country == 'USA') / n(),
            international = sum(country != 'USA') / n())
```

For nationals:
```{r}
levels_state <- marathon %>% 
          filter(!is.na(state) & country == 'USA' & state != 'NY' & year == 2018) %>% 
          group_by(state_name) %>% summarise(n=n()) %>% 
          arrange(n) %>% 
  select(state_name) %>% flatten_chr()

total <- marathon %>% 
  filter(!is.na(state) & country == 'USA' & state != 'NY') %>% 
  mutate(state_name =  factor(state_name, levels = levels_state)) %>% 
  nrow()

marathon %>% 
  filter(!is.na(state) & country == 'USA' & state != 'NY') %>% 
  mutate(state_name =  factor(state_name, levels = levels_state)) %>%
  group_by(year, state_name, type) %>% 
  summarise(count = n() / total) %>% 
  filter(type=='R') %>% 
  ggplot(aes(x=state_name, y=count)) + 
  geom_bar(stat = "identity", position = position_dodge()) +
  coord_flip() +
  theme_minimal() +
  facet_wrap(~year)

```


```{r}
library(maps)
library(geosphere)
library(mapproj)


marathon_cities <- marathon %>% 
  filter( country != 'USA' & year == 2018) %>% 
  group_by(city, lat, long) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))
maxcnt <- max(marathon_cities$count)  

par(mar=c(0,0,0,0))
map('world',col="white", fill=TRUE, bg="white", 
    projection="rectangular",parameter=0, 
    orientation=c(90,90,180), wrap=TRUE,
    resolution=0,
    lwd=0.08, mar=rep(0,1),border=1, ylim=c(-80,80) )


pal <- colorRampPalette(c("#d9d9d9", "black"))
#pal <- colorRampPalette(c("yellow", "red"))
colors <- pal(100)

ny_coords <- mapproject(-73.94, 40.67, proj="rectangular", parameter=0,orientation=c(90,90,180))
for (j in 1:nrow(marathon_cities)) {
  long = marathon_cities[j,]$long
  lat = marathon_cities[j,]$lat
  if (!is.na(lat) > 0 & !is.na(lat)) {
    coords <- mapproject(long, lat, proj="rectangular", parameter=0,orientation=c(90,90,180))
    inter <- gcIntermediate(c(ny_coords$x, ny_coords$y), c( coords$x, coords$y), n = 500, addStartEnd = TRUE)
    colindex <- round(((marathon_cities[j, ]$count/maxcnt) + 1 * length(colors)))
    color_alpha = color_transparent <- adjustcolor("turquoise2", alpha.f = 0.3) 
    #lines(inter, col="turquoise2", lwd = 0.08)
    lines(inter, col= color_alpha, lwd=0.1)
  }
  }
```


### Women Ratio


```{r}
marathon %>% 
  filter(!is.na(gender)) %>% 
  group_by(year, type) %>% 
  summarise(F = sum(gender=='F'),
            M = sum(gender=='M'),
            ratio = F/M)
```


```{r}
marathon %>% 
  filter(type == 'R') %>% 
  filter(country != 'NA') %>% 
  group_by(country, year) %>% 
  summarise(n = n(),
            num_male = sum(gender == 'M', na.rm=TRUE),
            num_female = sum(gender == 'F', na.rm=TRUE),
            ratio_gender = num_female / num_male) %>% 
  filter(n > 50) %>% 
  arrange(desc(ratio_gender)) %>% 
  ggplot(aes(x = ratio_gender,
             y = fct_reorder2(country, year ==2018, ratio_gender, .desc=FALSE),
             color = factor(year))) +
  geom_point(size=0.7) + 
  geom_vline(xintercept=1, color='#660066') + 
  ggtitle("Ratio of woman and men by country") +
  #scale_x_continuous(breaks = round(seq(0, 1.7, by = 0.2),1)) + #limits=c(0.1, 2)) +
  theme(panel.background = element_rect(fill = "white", colour = "lightgray"),
  panel.grid.major.x = element_blank() ,
  panel.grid.major.y = element_line(linetype=3, color="lightgray", size=0.4), axis.text.y = element_text(size=rel(0.7)),
  axis.title.y = element_blank())
```

By national
```{r}
marathon %>% 
  filter(type == 'R') %>%
  filter(state_name != 'NA') %>% 
  group_by(state_name, year) %>% 
  summarise(n = n(),
            num_male = sum(gender == 'M', na.rm=TRUE),
            num_female = sum(gender == 'F', na.rm=TRUE),
            ratio_gender = num_female / num_male) %>% 
  filter(n > 50) %>% 
  arrange(desc(ratio_gender)) %>% 
  ggplot(aes(x = ratio_gender, 
             y = fct_reorder2(state_name, year ==2018, ratio_gender, .desc=FALSE),
             color = factor(year))) +
  geom_point(size=0.7) +
  geom_vline(xintercept=1, color='#660066') + 
  ggtitle("Ratio of woman and men by state") +
  #scale_x_continuous(breaks = round(seq(0, 1.7, by = 0.2),1), limits=c(0.1, 1.8)) +
  theme(panel.background = element_rect(fill = "white", colour = "lightgray"),
  panel.grid.major.x = element_blank() ,
  panel.grid.major.y = element_line(linetype=3, color="lightgray", size=0.4), axis.text.y = element_text(size=rel(0.7)),
  axis.title.y = element_blank())
```

